# Generated by Django 6.1 on 2026-08-29 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Short display name for the habit, e.g. 'Drink water'.", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional longer explanation / motivation for the habit.')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='DAILY', help_text='How often this habit is expected to be performed.', max_length=10)),
                ('tracking_type', models.CharField(choices=[('BOOLEAN', 'Boolean (done / not done)'), ('NUMERIC', 'Numeric (integer count)')], default='BOOLEAN', help_text="How progress is logged for this habit: BOOLEAN for simple done/not-done habits (e.g. 'Meditated'), or NUMERIC for habits tracked by an integer count against target_count (e.g. 'Drink 8 glasses of water').", max_length=10)),
                ('target_count', models.PositiveIntegerField(default=1, help_text='Target number of units to complete per occurrence. Only meaningful when tracking_type=NUMERIC, e.g. 8 (glasses of water) or 30 (minutes of reading); ignored (treated as 1) for BOOLEAN habits.')),
                ('unit', models.CharField(blank=True, default='', help_text="Unit of measurement for target_count, e.g. 'glasses', 'pages'. Only relevant when tracking_type=NUMERIC.", max_length=50)),
                ('active', models.BooleanField(default=True, help_text='Whether this habit is currently being tracked.')),
                ('color_hex', models.CharField(default='#3498db', help_text="Hex color code (e.g. '#3498db') used for UI theming.", max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The owner of this habit.', on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The calendar date this log entry applies to.')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('MISSED', 'Missed')], default='MISSED', help_text='Whether the habit was completed, skipped, or missed on this date.', max_length=10)),
                ('value_achieved', models.FloatField(blank=True, help_text='Optional actual amount achieved, e.g. 7 out of a target_count of 8 glasses.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text="Optional free-text notes for this day's entry.")),
                ('habit', models.ForeignKey(help_text='The habit this log entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_habit_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='habitlog',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_log_per_habit_per_day'),
        ),
    ]
